# Generated by Django 3.2 on 2022-03-09 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Assigned_Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='assigned_tutors',
            field=models.ManyToManyField(blank=True, related_name='assigned_tutors', through='api.Assigned_Tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
