# Generated by Django 3.2 on 2022-03-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220309_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.course'),
        ),
    ]
