# Generated by Django 3.2 on 2022-03-10 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_assigned_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_course',
        ),
        migrations.AlterField(
            model_name='course',
            name='assigned_tutors',
            field=models.ManyToManyField(blank=True, related_name='tutors', through='api.Assigned_Tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
