# Generated by Django 3.2 on 2022-03-12 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220311_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Completed_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_complete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_complete', to='api.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='completed_module',
            field=models.ManyToManyField(blank=True, related_name='module_students', through='api.Completed_Module', to=settings.AUTH_USER_MODEL),
        ),
    ]
