# Generated by Django 3.2 on 2022-03-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220312_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='completed',
            field=models.CharField(default='', max_length=100),
        ),
    ]
