# Generated by Django 3.2 on 2022-03-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='../../media/images/default.png', upload_to='images/'),
        ),
    ]
